// Code generated by "stringer -type=SPAFunctions"; DO NOT EDIT.

package spa

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SpaZa-0]
	_ = x[SpaZaInc-1]
	_ = x[SpaZaRts-2]
	_ = x[SpaAll-3]
}

const _SPAFunctions_name = "SpaZaSpaZaIncSpaZaRtsSpaAll"

var _SPAFunctions_index = [...]uint8{0, 5, 13, 21, 27}

func (i SPAFunctions) String() string {
	if i >= SPAFunctions(len(_SPAFunctions_index)-1) {
		return "SPAFunctions(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SPAFunctions_name[_SPAFunctions_index[i]:_SPAFunctions_index[i+1]]
}
